### ISSUE TITLE
ccs

### ISSUE THREAD

**Issue by mhsieh** [mhsieh/pitchfork#18]

**Comment by mjhsieh** [comment]
This provides a way to use different branch of pbccs
```
$ make -C ports/pacbio/pbccs do-uninstall
$ make pbccs pbccs_VERSION=60c7b32  
```

**Comment by dalexander** [comment]
I like this.  Now one more question.  Is there a way to build ccs, using a different version of ConsensusCore2?  

`make pbcccs ConsensusCore2_VERSION=xxx` ?

**Comment by mhsieh** [comment]
Will work on this after lunch.

Best,
--mj
