### ISSUE TITLE
blasr_libcpp is broken on the Mac.

### ISSUE THREAD

**Issue by mhsieh** [mhsieh/pitchfork#30]
error on linking *.dylib

**Comment by mhsieh** [comment]
Enabled the shared version of library on for PBBAM, still doesn't work.

**Comment by mjhsieh** [comment]
g++ -dynamiclib -flat_namespace -L/opt/pitchfork/deployment/lib -L/opt/pitchfork/deployment/lib -L/opt/pitchfork/deployment/src/htslib -o libpbdata.dylib -Wl,-install_name,libpbdata.dylib CmpAlignment.shared.o AfgBasWriter.shared.o CCSSequence.shared.o ChangeListID.shared.o CommandLineParser.shared.o DNASequence.shared.o FASTAReader.shared.o FASTASequence.shared.o FASTQReader.shared.o FASTQSequence.shared.o GFFFile.shared.o MetricField.shared.o MovieAlnIndexLookupTable.shared.o MD5Utils.shared.o TitleTable.shared.o NucConversion.shared.o PackedDNASequence.shared.o QualityTransform.shared.o QualityValue.shared.o AcqParams.shared.o BaseFile.shared.o HoleXY.shared.o PulseBaseCommon.shared.o PulseFile.shared.o ReadType.shared.o RegionAnnotation.shared.o RegionAnnotations.shared.o RegionTable.shared.o RegionTypeMap.shared.o ScanData.shared.o ZMWGroupEntry.shared.o ReverseCompressIndex.shared.o AlnGroup.shared.o MovieInfo.shared.o RefGroup.shared.o RefInfo.shared.o ReadGroup.shared.o ReferenceSequence.shared.o SAMAlignment.shared.o SAMHeader.shared.o SAMKeywordValuePair.shared.o SMRTSequence.shared.o StringUtils.shared.o BitUtils.shared.o SMRTReadUtils.shared.o SMRTTitle.shared.o TimeUtils.shared.o 
Undefined symbols for architecture x86_64:

**Comment by mhsieh** [comment]
fixed
