### ISSUE TITLE
PREFIX writes relative to $HOME

### ISSUE THREAD

**Issue by mpkocher** [mhsieh/pitchfork#42]
Setting `make PREFIX=/tmp/pitchfork blasr` seems to be writing relative to $HOME. Not sure if this is the expected output.

I'm seeing this in the stdout:

=== configuring in htslib-1.3 (/Users/mkocher/tmp/pitchfork/workspace/samtools-1.3/htslib-1.3)

**Comment by mhsieh** [comment]
Definitely not, must be a bug...
Best,
--mj

**Comment by mhsieh** [comment]
Please try `PREFIX=/tmp/pitchfork make blasr `for now

**Comment by mhsieh** [comment]
I see, you cloned your pitchfork at $HOME/tmp/pitchfork right?

**Comment by mpkocher** [comment]
This is a user error on my end. The pbbam and pbccs targets work for me on OS X and exes are written to /tmp/pitckfork/bin.
