### ISSUE TITLE
Is building python from source a paranoia or a waste of efforts?

### ISSUE THREAD

**Issue by mhsieh** [mhsieh/pitchfork#56]

**Comment by mpkocher** [comment]
Perhaps building a virtualenv on top of the user's python 2.7 would be easier?

**Comment by mhsieh** [comment]
possible goal: Enable virutalenv on the Mac (or any Linux that use 2.7 for system python)

**Comment by mhsieh** [comment]
a3657393dcea7520aeff956909fc38344df0d254 is ready, you just need to do this:
```make PYVE=<noneEmptyString> python``` to have virtuelenv running.

**Comment by mhsieh** [comment]
next step: turn on PYVE if your system python is 2.7

**Comment by mhsieh** [comment]
```
mjs-macbook-pro:pitchfork mhsieh$ bin/chkSysPython 
mjs-macbook-pro:pitchfork mhsieh$ echo $?
0
```
