### ISSUE TITLE
GenomicConsensus

### ISSUE THREAD

**Issue by dalexander** [mhsieh/pitchfork#81]
We can work with you to get GC in here

**Comment by dalexander** [comment]
i think ideally we want ports for ConsensusCore, ConsensusCore2, because these (the latter, anyway) will be shared with pbccs

**Comment by mhsieh** [comment]
This will be a priority.

**Comment by mhsieh** [comment]
pbccs already includes ConsensusCore2

**Comment by mhsieh** [comment]
need swig first

**Comment by mhsieh** [comment]
this will need a full boost installation instead of a header collection.

**Comment by mjhsieh** [comment]
ConsensusCore done

**Comment by mjhsieh** [comment]
ConsensusCore2 done

**Comment by mhsieh** [comment]
GenomicConsensus done
